name: CI
on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        node_version:
          - 14
        node_arch:
          - x64
        include:
          - os: windows-latest
            node_version: 14
            node_arch: x86
          # - os: macos-11.0
          #   node_version: 15
          #   node_arch: arm64
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_arch }}

      - name: Install Dependencies and Build
        run: npm install

      - name: Prebuildify x64
        if: ${{ contains(matrix.node_arch, 'x64') }}
        run: npm run prebuildify

      - name: Prebuildify x86
        if: ${{ contains(matrix.node_arch, 'x86') }}
        run: npm run prebuildify-ia32

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./prebuilds

  Skip:
    if: contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
